"""
generated by claude + deepseek
Day 2 Challenge: Upgrade the day 1 webpage summarizer to use Ollama (local open-source LLM)
instead of OpenAI.

Usage with uv (from project root):
    uv run python week1/lubo-day2-solution.py <url>

Or from week1/:
    cd week1 && uv run -- python lubo-day2-solution.py <url>

Requirements:
    - Ollama running locally (http://localhost:11434)
    - Model pulled: ollama pull llama3.2
    - Dependencies: openai, beautifulsoup4, requests (all in pyproject.toml)
"""

import sys
from openai import OpenAI
from scraper import fetch_website_contents

OLLAMA_BASE_URL = "http://localhost:11434/v1"
MODEL = "llama3.2"

SYSTEM_PROMPT = """
You are a snarky assistant that analyzes the contents of a website,
and provides a short, snarky, humorous summary, ignoring text that might be navigation related.
Respond in markdown. Do not wrap the markdown in a code block - respond just with the markdown.
"""

USER_PROMPT_PREFIX = """
Here are the contents of a website.
Provide a short summary of this website.
If it includes news or announcements, then summarize these too.
"""


def messages_for(website_text: str) -> list[dict]:
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": USER_PROMPT_PREFIX + website_text},
    ]


def summarize(url: str) -> str:
    client = OpenAI(base_url=OLLAMA_BASE_URL, api_key="ollama")
    website_text = fetch_website_contents(url)
    response = client.chat.completions.create(
        model=MODEL,
        messages=messages_for(website_text),
    )
    return response.choices[0].message.content


def main():
    if len(sys.argv) < 2:
        url = "https://edwarddonner.com"
        print(f"No URL provided. Defaulting to: {url}")
    else:
        url = sys.argv[1]

    print(f"Summarizing {url} using {MODEL} via Ollama...")
    print()

    try:
        summary = summarize(url)
        print(summary)
    except Exception as e:
        print(f"Error: {e}")
        print()
        print("Make sure Ollama is running (http://localhost:11434) and the model is pulled:")
        print("  ollama serve")
        print(f"  ollama pull {MODEL}")
        sys.exit(1)


if __name__ == "__main__":
    main()